require("ahmed.packer-setup")
require("ahmed.core.set")
require("ahmed.core.remaps")
require("ahmed.after.colorscheme")
require("ahmed.after.treesitter")
require("ahmed.after.lsp-setup")
require("ahmed.after.auto-pairs")
require("ahmed.after.nvim-tree")
